return {
	{
		"romgrk/barbar.nvim",
		dependencies = {
			"lewis6991/gitsigns.nvim",
			"nvim-tree/nvim-web-devicons",
		},
		lazy = false,
		init = function() vim.g.barbar_auto_setup = true end,
		version = "^1.0.0",
		opts = {},
		keys = {
			{ "<leader>bq",  "<cmd>BufferClose<cr>",       desc = "Close current buffer" },
			{ "<leader>bt",  "<cmd>tabnew<cr>",            desc = "Open new buffer" },
			{ "<A-Left>",    "<cmd>BufferPrevious<cr>" },
			{ "<A-Right>",   "<cmd>BufferNext<cr>" },
			{ "<A-S-Left>",  "<cmd>BufferMovePrevious<cr>" },
			{ "<A-S-Right>", "<cmd>BufferMoveNext<cr>" },
			{ "<A-1>",       "<cmd>BufferGoto 1<cr>" },
			{ "<A-2>",       "<cmd>BufferGoto 2<cr>" },
			{ "<A-3>",       "<cmd>BufferGoto 3<cr>" },
			{ "<A-4>",       "<cmd>BufferGoto 4<cr>" },
			{ "<A-5>",       "<cmd>BufferGoto 5<cr>" },
			{ "<A-6>",       "<cmd>BufferGoto 6<cr>" },
			{ "<A-7>",       "<cmd>BufferGoto 7<cr>" },
			{ "<A-8>",       "<cmd>BufferGoto 8<cr>" },
			{ "<A-9>",       "<cmd>BufferGoto 9<cr>" },
			{ "<A-0>",       "<cmd>BufferLast<cr>" },
		},
	},
}
